hotel_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('system.urls')),
]

system/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('index', views.index, name='index'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', views.login, name='login'),
    path('acc', views.acc, name='acc'), 
    path('acc/expenses', views.expenses, name='expenses'), 
    path('acc/income', views.income, name='income'), 
    path('cuscha', views.cuscha, name='cuscha'),
    path('cusapa', views.cusapa, name='cusapa'),
    path('acc/mortgaga', views.mortgaga, name='mortgaga'), 
    path('clint',views.client, name='client'),
    path('apdate/<int:id>', views.apdateclientdataa, name='apdateclientdataa'),
    path('<int:id>', views.st_mor, name='st_mor'),
    path('clintdata',views.clientdata, name='clientdata'),
    path('services',views.services, name='services'),
    path('done_tasks',views.done_tasks, name='done_tasks'),
    path('tasks',views.tasks, name='tasks'),
    path('contents/<int:id>',views.contents, name='contents'),
    path('apartment_book/<int:id>',views.apartment_book, name='apartment_book'),
    path('validateresapa', views.validateresapa, name='validateresapa'),
    path('chalih_book/<int:id>',views.chalih_book, name='chalih_book'),
    path('validate', views.validate, name='validate'),
    path('validaterescha', views.validaterescha, name='validaterescha'),
    path('daterescha', views.daterescha, name='daterescha'),
    path('chalih_people/<int:id>',views.chalih_people, name='chalih_people'),
    path('donebookings',views.donebookings, name='donebookings'),
    path('chalih_bookings',views.chalih_bookings, name='chalih_bookings'),
    path('apartment_bookings',views.apartment_bookings, name='apartment_bookings'),
    path('apdate_apartment_book/<int:id>',views.apdate_apartment_book, name='apdate_apartment_book'),
    path('apdate_chalih_book/<int:id>',views.apdate_chalih_book, name='apdate_chalih_book'),
    path('get_dates',views.get_dates, name='get_dates'),
    path('bill/<int:id>',views.bill, name='bill'),
    path('reports',views.reports, name='reports'),
    path('bills',views.bills, name='bills'),
    path('out/<int:id>',views.out, name='out'),
    path('report',views.report, name='report'),
    path('acc_records',views.acc_records, name='acc_records'),
    path('customer_record',views.customer_record, name='customer_record'),
    path('rent_records',views.rent_records, name='rent_records'),
    path('book_cha',views.book_cha, name='book_cha'),
    path('validate_card',views.validate_card, name='validate_card'),
    path('validate_card2',views.validate_card2, name='validate_card2'),
    path('book_apa',views.book_apa, name='book_apa'),
    path('print_card/<int:id>',views.print_card, name='print_card'),
    path('check_people/', views.check_people, name='check_people'),
    path('entering_people/<int:booking_id>/', views.entering_people, name='entering_people'),
    path('save_person/', views.save_person, name='save_person'),
    path('settings', views.settings, name='settings'),
    path('mor', views.mor, name='mor'),

]

system/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from datetime import date
# Create your models here.

class Firm(models.Model):
    f_logo = models.ImageField(null=False,verbose_name='شعار الموسسه')
    f_name_ar = models.CharField(max_length=100,null=False,verbose_name='اسم الموسسه ar')
    f_name_en = models.CharField(max_length=100,null=False,verbose_name=' اسم الموسسه en')
    f_address_ar = models.CharField(max_length=100,null=False,verbose_name='العنوان ar')
    f_address_en = models.CharField(max_length=100,null=False,verbose_name='العنوان en')
    f_phon_ar = models.IntegerField(null=False,verbose_name='الرقم')
    f_phon_en = models.IntegerField(null=False,verbose_name='الرقم')

    def __str__(self): 
         return self.f_name_ar
    
    class Meta:
         verbose_name_plural = 'الموسسه'
         verbose_name = 'البيانات'

class Branch(models.Model):
    bra_name = models.CharField(max_length=20,null=False,verbose_name='اسم الفرع')
    bra_address = models.CharField(max_length=20,null=False,verbose_name='عنوان الفرع')
    bra_add_datetime = models.DateTimeField(default=datetime.now,verbose_name='تاريخ ووقت الأضافه')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user',verbose_name=' المستخدم')

    def __str__(self): 
         return self.bra_name
    
    class Meta:
         verbose_name_plural = 'الفروع'
         verbose_name = 'فرع'


class Towers(models.Model):
     Branch = models.ForeignKey(Branch,on_delete=models.CASCADE,verbose_name='الفرع')
     tow_name = models.CharField(max_length=20,null=False,verbose_name='اسم البرج')
     tow_floornumber = models.IntegerField(null=False,verbose_name='عدد الطوابق')
     tow_add_datetime = models.DateTimeField(default=datetime.now,verbose_name='تاريخ ووقت الأضافه')
     user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name=' المستخدم')

     def __str__(self): 
         return self.tow_name
     
     class Meta:
         verbose_name_plural = 'البرج'
         verbose_name = 'برج'


class Apartmint_chalit(models.Model):
     towers = models.ForeignKey(Towers,on_delete=models.CASCADE,verbose_name='البرج')
     apa_cha_status = models.BooleanField(null=True,verbose_name='الحاله')

     def __str__(self): 
         return 'LOCATION IN {SELF.Towers.tow_name}'
     
     class Meta:
         verbose_name_plural = 'الشقق والشاليهات'
         verbose_name = 'شقه او شاليه'

              
class Apartments(Apartmint_chalit):
     apa_name = models.CharField(max_length=20,null=False,verbose_name='اسم الشقه')
     apa_floor = models.CharField(max_length=20,null=True,verbose_name='الطابق')
     apa_price = models.DecimalField(max_digits=10,decimal_places=2,null=False,verbose_name='السعر')
     apa_discrip = models.TextField(max_length=50,null=True,verbose_name='الوصف')
     apa_status = models.BooleanField(null=True,verbose_name='الحاله')
     apa_add_datetime = models.DateTimeField(default=datetime.now,verbose_name='تاريخ ووقت الأضافه')
     user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='المستخدم')

     def __str__(self): 
         return self.apa_name
     
     class Meta:
         verbose_name_plural = 'الشقق'
         verbose_name = 'شقه'
     

class Chalets(Apartmint_chalit):
     cha_name = models.CharField(max_length=20,null=False,verbose_name='اسم الشاليه')
     cha_floor = models.CharField(max_length=20,null=True,verbose_name='الطابق')
     cha_discrip = models.TextField(max_length=50,null=True,verbose_name='الوصف')
     cha_status = models.BooleanField(default=True)
     cha_add_datetime = models.DateTimeField(default=datetime.now,verbose_name='تاريخ ووقت الأضافه')
     user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='المستخدم')

     def __str__(self): 
         return self.cha_name
     
     class Meta:
         verbose_name_plural = 'الشاليهات'
         verbose_name = 'شاليه'
     

class Bunch(models.Model): 
     bun_name = models.CharField(max_length=50,null=False,verbose_name='اسم الباقه')
     bun_people_number = models.IntegerField(null=True,verbose_name='عدد الأشخاص')
     bun_entrytime = models.TimeField(null=True,verbose_name='وقت الدخول')
     bun_exittime = models.TimeField(null=True,verbose_name='وقت الخروج')
     bun_price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='السعر')
     addpeo_price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='سعر الاأشخاص الأضافيين')
     bun_childprice = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='سعر الأطفال') 
     bun_add_datetime = models.DateTimeField(default=datetime.now,verbose_name='تاريخ ووقت الأضافه')
     user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='المستخدم')

     def __str__(self): 
         return self.bun_name
     
     class Meta:
         verbose_name_plural = 'الباقات'
         verbose_name = 'باقه'
     

class People(models.Model):
     status = [
         ('enter','تم الدخول'),
         ('notenter','لم يتم الدخول'),
              ]

     reservecha = models.ForeignKey('Reservecha',on_delete=models.CASCADE,verbose_name='اسم الحجز')
     peo_name = models.CharField(max_length=50,null=False,verbose_name='الأسم')
     peo_age = models.IntegerField(null=False,verbose_name='العمر')
     peo_card_number = models.IntegerField(null=True,verbose_name='رقم البطاقه')
     peo_add_datetime = models.DateTimeField(default=datetime.now,verbose_name='تاريخ ووقت الأضافه')
     st_people = models.CharField(max_length=20, choices=status, null=True, verbose_name='الحاله',default= 'notenter')
     user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='المستخدم',default='abdalrahman')

     def __str__(self): 
         return self.peo_name
     
     class Meta:
         verbose_name_plural = 'الأشخاص'
         verbose_name = 'شخص'
     
class Customers(models.Model):
     cus_name = models.CharField(max_length=50,null=False,verbose_name='اسم العميل')
     cus_card_id = models.IntegerField(null=False,verbose_name='رقم البطاقه')
     cus_phone_number = models.IntegerField(null=False,verbose_name='رقم التلفون')
     cus_address = models.CharField(max_length=20,null=True,verbose_name='العنوان')
     cus_age = models.IntegerField(null=True,verbose_name='العمر')
     cus_gender = models.CharField(max_length=10,null=True,verbose_name='الجنس')
     cus_add_datetime = models.DateTimeField(default=datetime.now,verbose_name='تاريخ ووقت الأضافه')
     user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='المستخدم')

     def __str__(self): 
         return self.cus_name
     
     class Meta:
         verbose_name_plural = 'العملاء'
         verbose_name = 'عميل'
     


class Reservecha(models.Model):
     
     status = [
         ('sure','مؤكد'),
         ('notsure','غير مؤكد'),
         ('cancel','ملغي'),
         ('done','منتهي'),
     ]

     chalits = models.ForeignKey(Chalets,on_delete=models.CASCADE,verbose_name='الشاليه')
     bunch = models.ForeignKey(Bunch,on_delete=models.CASCADE,verbose_name='نوع الباقه')
     customers = models.ForeignKey(Customers,on_delete=models.CASCADE,verbose_name='اسم العميل')
     res_cha_date = models.DateField(null=False,verbose_name='تاريخ الحجز', default=datetime.now)
     login_time = models.TimeField(null=False,verbose_name='وقت الدخول')
     exit_time = models.TimeField(null=False,verbose_name='وقت الخروج')
     res_cha_price = models.DecimalField(max_digits=10,decimal_places=2,null=False,verbose_name='السعر')
     add_datetime = models.DateTimeField(default=datetime.now,verbose_name='تاريخ ووقت الأضافه')
     user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='المستخدم',default='abdalrahman')
     st_book = models.CharField(max_length=20, choices=status, null=True, verbose_name='الحاله',default= 'notsure')
     def __str__(self): 
         return self.customers.cus_name
     
     
         
     class Meta:
         verbose_name_plural = 'حجز شاليه'
         verbose_name = 'حجز '


class Check(models.Model):
     reservecha = models.ForeignKey(Reservecha,on_delete=models.CASCADE,verbose_name='اسم الحجز')
     che_status = models.BooleanField(verbose_name='الحاله')
     che_date = models.DateField(null=False,verbose_name='التاريخ')
     che_add_datetime = models.DateTimeField(default=datetime.now,verbose_name='تاريخ ووقت الأضافه') 
     user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='المستخدم')

     def __str__(self): 
         return self.reservecha.customers.cus_name
     
     class Meta:
         verbose_name_plural = 'الفحص'
         verbose_name = 'فحص'
     

class Content(models.Model):
     chalit = models.ForeignKey(Chalets,on_delete=models.CASCADE,null=True,verbose_name=' الشاليهات')
     con_name = models.CharField(max_length=50,null=False,verbose_name='المحتوى')
     con_price = models.DecimalField(max_digits=10,decimal_places=2,null=False,verbose_name='السعر')
     con_add_datetime = models.DateTimeField(default=datetime.now,verbose_name='تاريخ ووقت الأضافه') 
     user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='المستخدم')

     def __str__(self): 
         return self.con_name
     
     class Meta:
         verbose_name_plural = 'المحتويات'
         verbose_name = 'المحتوى'
         
     

class Fund(models.Model):
     fun_name = models.CharField(max_length=30,null=False,verbose_name='اسم الصندوق')
     fun_add_datetime = models.DateTimeField(default=datetime.now,verbose_name='تاريخ ووقت الأضافه')
     user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='المستخدم')

     def __str__(self): 
         return self.fun_name
     
     class Meta:
         verbose_name_plural = 'الصندوق'
         verbose_name = 'صندوق'
     

     

class Mortgage(models.Model):
     fund = models.ForeignKey(Fund,on_delete=models.CASCADE,verbose_name='الصندوق')

templates/pages/accounts/acc.html
{% extends 'base.html' %}

{% block content%}


  <div class="acc-card-container">
    <a href="{% url 'expenses' %}" class="btn" >
		<div class="acc-card">
			<div class="acc-card-content">
				<h3>المصروفات </h3>
			</div>
		</div>
    </a>
  </div>

  <div class="acc-card-container">
    <a href="{% url 'income' %}" class="btn" >
		<div class="acc-card">
			<div class="acc-card-content">
				<h3>المقبوضات</h3>
			</div>
		</div>
    </a>
  </div>
  
  <div class="acc-card-container">
    <a href="{% url 'mor' %}" class="btn" >
		<div class="acc-card">
			<div class="acc-card-content">
				<h3>الرهونات</h3>
			</div>
		</div>
    </a>
  </div>

  {% endblock %}

   

templates/pages/accounts/expenses.html
{% extends 'base.html' %}

  
  
{% block content%}


 <dev class="allform">
  <form  method="POST">
    {% csrf_token %}
      <div class="container">

        <div class="input-field">
          <label for="nationality">{{form.fund.label}} </label>
          {{form.fund}}
        </div>
      </div>

      <div class="container">


        <div class="input-field">
          <label for="date-of-arrival">التاريخ</label>
          {{form.pay_date}}
        </div>

      <div class="input-field">
        <label >النوع</label>
        <select id="type" >
          
          <option value="apa">مصروفات عامة</option>
          <option value="cha">مرتجع حجز</option>
        </select>
      </div>
    </div>
</div>
    <div class="section">

        <div class="container">

          <div class="input-field">
            <label>المبلغ</label>
            {{form.pay_amountoutside}}
          </div>

      <div class="input-field">
        <label>لاجل</label>
        {{form.f_or}}
      </div>
    </div>

    <div class="container">

      <div class="input-field">
        <label>اسم المستلم</label>
        {{form.recipient_name}}
      </div>

 
      <div class="input-field">
        <label for="id-number">ملاحظات</label>
        {{form.pay_notice}}
      </div>
</div>
</div>
   

    <div class="button-container">
      <button type="submit" class="button">حفظ</button>
    </div>

  </form>
 </dev>

 {% endblock %}

templates/pages/accounts/income.html
{% extends 'base.html' %}

{% block content%}


 <dev class="allform">
  <form  method="POST">
    {% csrf_token %}
      <div class="container">

        <div class="input-field">
          <label for="nationality">{{form.fund.label}}</label>
          {{form.fund}}
        </div>
      </div>

      <div class="container">


        <div class="input-field">
          <label for="date-of-arrival">التاريخ</label>
          {{form.pay_date}}
        </div>

      <div class="input-field">
        <label >الحجز</label>
        <select id="reserve" >
          
          <option value="apa">شقه</option>
          <option value="cha">شاليه</option>
        </select>
      </div>
    </div>
</div>
    <div class="section">

        <div class="container">

          <div class="input-field">
            <label for="id-number">المبلغ </label>
            {{form.pay_amountinside}}
          </div>

      <div class="input-field">
        <label for="id-number">رقم الحجز</label>
        {{form.reservecha}}
        {{form.reserveape}}
      </div>
    </div>

    <div class="container">

      <div class="input-field">
        <label for="id-number">استلمت بواسطة</label>
        {{form.user}}
      </div>

 
      <div class="input-field">
        <label for="nationality">اسم العميل</label>
        {{form.customers}}
      </div>
</div>
</div>
    <div class="section">

      <div class="input-field">
        <label for="id-number">ملاحظات</label>
        {{form.pay_notice}}
      </div>

    </div>

    <div class="button-container">
      <button type="submit" class="button">حفظ</button>
    </div>
    <div style="display: none;">
      {{form.pay_amountoutside}}
    </div>
  </form>
 </dev>

 {% endblock %}
 {% block javascript %}
 <script>
  $("#reserve").change(function(){
    var vv = $(this).val();
    if (vv == "cha"){
      $("#id_reservecha").show();
      $("#id_reserveape").hide();
     
    }
    else {
      $("#id_reservecha").hide();
      $("#id_reserveape").show();
      $("#id_reserveape").change(function(){
         var idresap = $(this).val();
        
      });
    }
  });
  $("#reserve").removeAttr("name");
 </script>
 <script>
  $("#id_reservecha").change(function(){
         var idresch = $(this).val();
         $.ajax({
          dataType:'json',
          url:'/cuscha',
          data:{'idresch':idresch},

          success: function(data){
            $("#id_customers").val(data.cname);
          }
         });
      });
 </script>
  <script>
    $("#id_reserveape").change(function(){
           var idresap = $(this).val();
           $.ajax({
            dataType:'json',
            url:'/cusapa',
            data:{'idresap':idresap},
  
            success: function(data){
              $("#id_customers").val(data.cname);
            }
           });
        });
   </script>
 {% endblock %}

templates/pages/accounts/mor.html
{% extends 'base.html' %}

{% block content%}

  <div class="cli-container">
    <div class="repos">
      <input type="text" placeholder="بحث" id="searchbox">
      <span class="cli-btn"><i class="fas fa-search"></i></span>
      <span class="cli-btn"><a href="{% url 'mortgaga' %}"><i class="fas fa-add"></i></a></span>
    </div>

  <div class="data" id="customer">
    {% for i in mor %}
    <div class="cusname" style="align-items: center;" id="cusname" title="cusname">
      <p class="p_cli" style="position: static;">{{i.id}}  :  {{i.reservecha}}</p>
	  <p class="p_cli" style="position: static; margin-right: 30%;"> {{i.mor_type}} </p>
      <div class="left_clt" style="position: absolute; right: 75%;  background-color: #247dcf; padding: 5px;border-radius: 5px;">
        <a href="{% url 'st_mor' i.id %}">
          <i name="apdate" method="POST">تسليم</i>
          {% csrf_token %}
        </a>
      </div> 
   
    </div>
    
    {% endfor %}
  </div>
  

 
 </div>

 {% endblock %}

  

templates/pages/accounts/mortgaga.html
{% extends 'base.html' %}

{% block content%}
<dev class="allform">
  <form  method="POST">
       {% csrf_token %}
      <div class="container">

        <div class="input-field">
          <label style="margin-right: 40%;">صندوق الرهونات </label>
          
        </div>
      </div>
      <label style="float: right; margin-right: 15%;">رقم الحجز</label>
      <input type="text" id="reserve_id" name="reservecha" style="width: 40%; float: right; margin-right: 5%;">
      <div class="container">
        
        <div class="input-field">
            <label>اسم الزبون</label>
            <input type="text" id="customers_id">
          </div>

        <div class="input-field">
          <label for="date-of-arrival">تاريخ</label>
          <input type="text" id="date-of-arrival" name="mor_date">
        </div>

    
    </div>
</div>
    <div class="section">

        <div class="container">
        
          

          <div class="input-field">
            <label for="nationality" >نوع الرهن</label>
            <select id="mo_type" name="mor_type" style=" float: right;">
              <option value="سلاح">سلاح</option>
              <option value="ذهب">ذهب</option>
              <option value="نقد">نقد</option>
            </select>
          </div>

          <div class="hide" id="mo_price">
          <div class="input-field">
            <label for="id-number">المبلغ</label>
            <input type="text" id="id-number" name="mor_amaunt" value="0.0">
          </div>
          </div>
         
    </div>

    <div class="container">

 
    
</div>
</div>
    <div class="section">

      <div class="input-field">
        <label for="id-number"> بيان الرهن (ملاحظات)</label>
        <input type="text" id="id-number" name="mor_notice">
      </div>

    </div>

    <div class="button-container">
      <button type="submit" class="button">حفظ</button>
    </div>

  </form>
</dev>  

  {% endblock %}

  {% block javascript %}
  <script>
    $("#reserve_id").change(function(){
           var idresch = $(this).val();
           $.ajax({
            dataType:'json',
            url:'/cuscha',
            data:{'idresch':idresch},
  
            success: function(data){
              $("#customers_id").val(data.cename);
            }
           });
        });
   </script>
    <script>
      $('#mo_type').change(function(){
       var ty = $(this).val(); 
       if(ty == "نقد"){
         $('#mo_price').show()         
       }
       else{
         $('#mo_price').hide()
       }
      })
     </script>
 {% endblock %}