hotel_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('system.urls')),
]

system/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('index', views.index, name='index'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', views.login, name='login'),
    path('acc', views.acc, name='acc'), 
    path('acc/expenses', views.expenses, name='expenses'), 
    path('acc/income', views.income, name='income'), 
    path('cuscha', views.cuscha, name='cuscha'),
    path('cusapa', views.cusapa, name='cusapa'),
    path('acc/mortgaga', views.mortgaga, name='mortgaga'), 
    path('clint',views.client, name='client'),
    path('apdate/<int:id>', views.apdateclientdataa, name='apdateclientdataa'),
    path('<int:id>', views.st_mor, name='st_mor'),
    path('clintdata',views.clientdata, name='clientdata'),
    path('services',views.services, name='services'),
    path('done_tasks',views.done_tasks, name='done_tasks'),
    path('tasks',views.tasks, name='tasks'),
    path('contents/<int:id>',views.contents, name='contents'),
    path('apartment_book/<int:id>',views.apartment_book, name='apartment_book'),
    path('validateresapa', views.validateresapa, name='validateresapa'),
    path('chalih_book/<int:id>',views.chalih_book, name='chalih_book'),
    path('validate', views.validate, name='validate'),
    path('validaterescha', views.validaterescha, name='validaterescha'),
    path('daterescha', views.daterescha, name='daterescha'),
    path('chalih_people/<int:id>',views.chalih_people, name='chalih_people'),
    path('donebookings',views.donebookings, name='donebookings'),
    path('chalih_bookings',views.chalih_bookings, name='chalih_bookings'),
    path('apartment_bookings',views.apartment_bookings, name='apartment_bookings'),
    path('apdate_apartment_book/<int:id>',views.apdate_apartment_book, name='apdate_apartment_book'),
    path('apdate_chalih_book/<int:id>',views.apdate_chalih_book, name='apdate_chalih_book'),
    path('get_dates',views.get_dates, name='get_dates'),
    path('bill/<int:id>',views.bill, name='bill'),
    path('reports',views.reports, name='reports'),
    path('bills',views.bills, name='bills'),
    path('out/<int:id>',views.out, name='out'),
    path('report',views.report, name='report'),
    path('acc_records',views.acc_records, name='acc_records'),
    path('customer_record',views.customer_record, name='customer_record'),
    path('rent_records',views.rent_records, name='rent_records'),
    path('book_cha',views.book_cha, name='book_cha'),
    path('validate_card',views.validate_card, name='validate_card'),
    path('validate_card2',views.validate_card2, name='validate_card2'),
    path('book_apa',views.book_apa, name='book_apa'),
    path('print_card/<int:id>',views.print_card, name='print_card'),
    path('check_people/', views.check_people, name='check_people'),
    path('entering_people/<int:booking_id>/', views.entering_people, name='entering_people'),
    path('save_person/', views.save_person, name='save_person'),
    path('settings', views.settings, name='settings'),
    path('mor', views.mor, name='mor'),

]

system/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from datetime import date
# Create your models here.

class Firm(models.Model):
    f_logo = models.ImageField(null=False,verbose_name='شعار الموسسه')
    f_name_ar = models.CharField(max_length=100,null=False,verbose_name='اسم الموسسه ar')
    f_name_en = models.CharField(max_length=100,null=False,verbose_name=' اسم الموسسه en')
    f_address_ar = models.CharField(max_length=100,null=False,verbose_name='العنوان ar')
    f_address_en = models.CharField(max_length=100,null=False,verbose_name='العنوان en')
    f_phon_ar = models.IntegerField(null=False,verbose_name='الرقم')
    f_phon_en = models.IntegerField(null=False,verbose_name='الرقم')

    def __str__(self): 
         return self.f_name_ar
    
    class Meta:
         verbose_name_plural = 'الموسسه'
         verbose_name = 'البيانات'

class Branch(models.Model):
    bra_name = models.CharField(max_length=20,null=False,verbose_name='اسم الفرع')
    bra_address = models.CharField(max_length=20,null=False,verbose_name='عنوان الفرع')
    bra_add_datetime = models.DateTimeField(default=datetime.now,verbose_name='تاريخ ووقت الأضافه')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user',verbose_name=' المستخدم')

    def __str__(self): 
         return self.bra_name
    
    class Meta:
         verbose_name_plural = 'الفروع'
         verbose_name = 'فرع'


class Towers(models.Model):
     Branch = models.ForeignKey(Branch,on_delete=models.CASCADE,verbose_name='الفرع')
     tow_name = models.CharField(max_length=20,null=False,verbose_name='اسم البرج')
     tow_floornumber = models.IntegerField(null=False,verbose_name='عدد الطوابق')
     tow_add_datetime = models.DateTimeField(default=datetime.now,verbose_name='تاريخ ووقت الأضافه')
     user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name=' المستخدم')

     def __str__(self): 
         return self.tow_name
     
     class Meta:
         verbose_name_plural = 'البرج'
         verbose_name = 'برج'


class Apartmint_chalit(models.Model):
     towers = models.ForeignKey(Towers,on_delete=models.CASCADE,verbose_name='البرج')
     apa_cha_status = models.BooleanField(null=True,verbose_name='الحاله')

     def __str__(self): 
         return 'LOCATION IN {SELF.Towers.tow_name}'
     
     class Meta:
         verbose_name_plural = 'الشقق والشاليهات'
         verbose_name = 'شقه او شاليه'

              
class Apartments(Apartmint_chalit):
     apa_name = models.CharField(max_length=20,null=False,verbose_name='اسم الشقه')
     apa_floor = models.CharField(max_length=20,null=True,verbose_name='الطابق')
     apa_price = models.DecimalField(max_digits=10,decimal_places=2,null=False,verbose_name='السعر')
     apa_discrip = models.TextField(max_length=50,null=True,verbose_name='الوصف')
     apa_status = models.BooleanField(null=True,verbose_name='الحاله')
     apa_add_datetime = models.DateTimeField(default=datetime.now,verbose_name='تاريخ ووقت الأضافه')
     user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='المستخدم')

     def __str__(self): 
         return self.apa_name
     
     class Meta:
         verbose_name_plural = 'الشقق'
         verbose_name = 'شقه'
     

class Chalets(Apartmint_chalit):
     cha_name = models.CharField(max_length=20,null=False,verbose_name='اسم الشاليه')
     cha_floor = models.CharField(max_length=20,null=True,verbose_name='الطابق')
     cha_discrip = models.TextField(max_length=50,null=True,verbose_name='الوصف')
     cha_status = models.BooleanField(default=True)
     cha_add_datetime = models.DateTimeField(default=datetime.now,verbose_name='تاريخ ووقت الأضافه')
     user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='المستخدم')

     def __str__(self): 
         return self.cha_name
     
     class Meta:
         verbose_name_plural = 'الشاليهات'
         verbose_name = 'شاليه'
     

class Bunch(models.Model): 
     bun_name = models.CharField(max_length=50,null=False,verbose_name='اسم الباقه')
     bun_people_number = models.IntegerField(null=True,verbose_name='عدد الأشخاص')
     bun_entrytime = models.TimeField(null=True,verbose_name='وقت الدخول')
     bun_exittime = models.TimeField(null=True,verbose_name='وقت الخروج')
     bun_price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='السعر')
     addpeo_price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='سعر الاأشخاص الأضافيين')
     bun_childprice = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='سعر الأطفال') 
     bun_add_datetime = models.DateTimeField(default=datetime.now,verbose_name='تاريخ ووقت الأضافه')
     user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='المستخدم')

     def __str__(self): 
         return self.bun_name
     
     class Meta:
         verbose_name_plural = 'الباقات'
         verbose_name = 'باقه'
     

class People(models.Model):
     status = [
         ('enter','تم الدخول'),
         ('notenter','لم يتم الدخول'),
              ]

     reservecha = models.ForeignKey('Reservecha',on_delete=models.CASCADE,verbose_name='اسم الحجز')
     peo_name = models.CharField(max_length=50,null=False,verbose_name='الأسم')
     peo_age = models.IntegerField(null=False,verbose_name='العمر')
     peo_card_number = models.IntegerField(null=True,verbose_name='رقم البطاقه')
     peo_add_datetime = models.DateTimeField(default=datetime.now,verbose_name='تاريخ ووقت الأضافه')
     st_people = models.CharField(max_length=20, choices=status, null=True, verbose_name='الحاله',default= 'notenter')
     user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='المستخدم',default='abdalrahman')

     def __str__(self): 
         return self.peo_name
     
     class Meta:
         verbose_name_plural = 'الأشخاص'
         verbose_name = 'شخص'
     
class Customers(models.Model):
     cus_name = models.CharField(max_length=50,null=False,verbose_name='اسم العميل')
     cus_card_id = models.IntegerField(null=False,verbose_name='رقم البطاقه')
     cus_phone_number = models.IntegerField(null=False,verbose_name='رقم التلفون')
     cus_address = models.CharField(max_length=20,null=True,verbose_name='العنوان')
     cus_age = models.IntegerField(null=True,verbose_name='العمر')
     cus_gender = models.CharField(max_length=10,null=True,verbose_name='الجنس')
     cus_add_datetime = models.DateTimeField(default=datetime.now,verbose_name='تاريخ ووقت الأضافه')
     user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='المستخدم')

     def __str__(self): 
         return self.cus_name
     
     class Meta:
         verbose_name_plural = 'العملاء'
         verbose_name = 'عميل'
     


class Reservecha(models.Model):
     
     status = [
         ('sure','مؤكد'),
         ('notsure','غير مؤكد'),
         ('cancel','ملغي'),
         ('done','منتهي'),
     ]

     chalits = models.ForeignKey(Chalets,on_delete=models.CASCADE,verbose_name='الشاليه')
     bunch = models.ForeignKey(Bunch,on_delete=models.CASCADE,verbose_name='نوع الباقه')
     customers = models.ForeignKey(Customers,on_delete=models.CASCADE,verbose_name='اسم العميل')
     res_cha_date = models.DateField(null=False,verbose_name='تاريخ الحجز', default=datetime.now)
     login_time = models.TimeField(null=False,verbose_name='وقت الدخول')
     exit_time = models.TimeField(null=False,verbose_name='وقت الخروج')
     res_cha_price = models.DecimalField(max_digits=10,decimal_places=2,null=False,verbose_name='السعر')
     add_datetime = models.DateTimeField(default=datetime.now,verbose_name='تاريخ ووقت الأضافه')
     user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='المستخدم',default='abdalrahman')
     st_book = models.CharField(max_length=20, choices=status, null=True, verbose_name='الحاله',default= 'notsure')
     def __str__(self): 
         return self.customers.cus_name
     
     
         
     class Meta:
         verbose_name_plural = 'حجز شاليه'
         verbose_name = 'حجز '


class Check(models.Model):
     reservecha = models.ForeignKey(Reservecha,on_delete=models.CASCADE,verbose_name='اسم الحجز')
     che_status = models.BooleanField(verbose_name='الحاله')
     che_date = models.DateField(null=False,verbose_name='التاريخ')
     che_add_datetime = models.DateTimeField(default=datetime.now,verbose_name='تاريخ ووقت الأضافه') 
     user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='المستخدم')

     def __str__(self): 
         return self.reservecha.customers.cus_name
     
     class Meta:
         verbose_name_plural = 'الفحص'
         verbose_name = 'فحص'
     

class Content(models.Model):
     chalit = models.ForeignKey(Chalets,on_delete=models.CASCADE,null=True,verbose_name=' الشاليهات')
     con_name = models.CharField(max_length=50,null=False,verbose_name='المحتوى')
     con_price = models.DecimalField(max_digits=10,decimal_places=2,null=False,verbose_name='السعر')
     con_add_datetime = models.DateTimeField(default=datetime.now,verbose_name='تاريخ ووقت الأضافه') 
     user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='المستخدم')

     def __str__(self): 
         return self.con_name
     
     class Meta:
         verbose_name_plural = 'المحتويات'
         verbose_name = 'المحتوى'
         
     

class Fund(models.Model):
     fun_name = models.CharField(max_length=30,null=False,verbose_name='اسم الصندوق')
     fun_add_datetime = models.DateTimeField(default=datetime.now,verbose_name='تاريخ ووقت الأضافه')
     user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='المستخدم')

     def __str__(self): 
         return self.fun_name
     
     class Meta:
         verbose_name_plural = 'الصندوق'
         verbose_name = 'صندوق'
     

     

class Mortgage(models.Model):
     fund = models.ForeignKey(Fund,on_delete=models.CASCADE,verbose_name='الصندوق')

templates/pages/booking/apartment_book.html
{% extends 'base.html' %}

{% block content%}

<form class="form_B1" method="POST" >
  {% csrf_token %}
    <div class="container_B2">

      <div class="input-field_B3">
          <label class="label_B4">{{form.customers.label}}</label>
          {{form.customers}}
          <a href="{% url 'clientdata' %}" style=" color: #000;">
          <i class="fas fa-add"></i> 
          </a>
      </div>
    </div>

  <div class="section_B5">
    <div class="input-field_B3" style="width: 250px;">
      <label class="label_B4">{{form.login_date.label}}</label>
      {{form.login_date}}
      <p id="error" style="font-size: small; float: right; margin-right: 8px; color: #f10202; display: none; margin-bottom: 0%;">هذا التاريخ محجوز </p>
    </div>
  </div>

  <div class="section_B5">
    <div class="input-field_B3" style="margin-right: 150px; margin-top: 20px; width: 250px;">
      <label class="label_B4">{{form.exit_date.label}}</label>
      {{form.exit_date}}
      <p id="errorex" style="font-size: small; margin-left: 155px; color: #f10202; display: none; margin-bottom: 0%;">التاريخ غير صالح</p>
    </div>
  </div>

  <div class="input-field_B3" style="margin-top: 1px; position: absolute; right: 10px;">
    <label class="label_B4" style="position: absolute; right: 20px;">{{form.res_price.label}}</label>
    {{form.res_price}}
  </div>
  <div>
  <label class="label_B9_1" style="position: absolute; top: 250px; left: 170px; font-size: larger;"> عدد الليالي : <span id="days">5</span> </label>
  
  </div>
  <div class="input-field_B3" style="margin-top: 20px; position: absolute;right: 5px; bottom: 60px; width: 600px;">
    <label class="label_B4" style="position: absolute; bottom: 50px;right: 28px; ">{{form.res_notice.label}}</label>
    {{form.res_notice}}
  </div>
  <div style="display: none;">
    {{form.apartments}}
    {{form.user}}
  </div>

  <div class="button-container_B6" style="position: absolute; bottom: 10px;width: 650px;">
    <button type="submit" class="button_b6">حجز الشقة</button>
  </div>
</form>

<div class="container_B9" style="height: 460px; width: 300px;" >
  <label class="label_B9" style="position: absolute; right: 5px;">معلومات الشقة</label> <br> <br>
  <hr>
  <label class="label_B9_1" style="position: absolute; right: 2px"> الطابق :   {{bookap.apa_floor}}</label>
  <label class="label_B9_1" style="position: absolute; left: 40px;">  {{bookap.apa_name}}  </label>
  <label class="label_B9_1" style="position: absolute; top: 150px; right: 2px; margin-top: 25px;"> وصف الشقة :{{bookap.apa_discrip}}  </label>
  <br> <br> <br> <br> <br> <br> <hr>
  <label class="label_B9_1" style="font-size: x-large;padding-top: 10px; position: absolute; right: 2px; bottom: 137px;"> الإجمالي  : </label> 
  <label class="label_B9_1" id="price" style="font-size: x-large; font-weight: bold; margin-top: 10px;position: absolute; right: 115px;bottom: 135px;">00.000 </label> <br>
  <label class="label_B9_1" style="font-size: larger;position: absolute; bottom: 80px; right: 2px;">المدفوع :</label>
  <label class="label_B9_1" style="font-size: larger; font-weight: bold; margin-top: 10px;position: absolute; right: 115px;bottom: 80px;">00.000 </label>
  <label class="label_B9_1" style="font-size: larger;position: absolute; bottom: 40px; right: 2px;">المتبقي :</label>
  <label class="label_B9_1" style="font-size: larger; font-weight: bold; margin-top: 10px;position: absolute; right: 115px;bottom: 40px;">00.000 </label>
  <input type="hidden" value="{{bookap.apa_price}} " id="apaprice">
</div>

{% endblock %}

{% block javascript %}
<script>
  $(document).ready(function(){
    $('#days').mouseenter(function(){
      const enterdate = new Date($('#id_login_date').val());
      const exitdate = new Date($('#id_exit_date').val());
      const oneday = 24 * 60 * 60 * 1000;
      const daysdiff = Math.floor((exitdate - enterdate) / oneday);
      $('#days').text(daysdiff);
      const apaprice = $('#apaprice').val();
      const totalprice = parseInt(daysdiff) * parseInt(apaprice);
      $('#id_res_price').val(totalprice);
      $('#price').text(totalprice);
    });
   
  });  
</script>
<script>
 
 $("#id_login_date").change(function(){
 var resdate = $(this).val();
 var apaid = $('#id_apartments').val();
 
 $.ajax({
  dataType:'json',
  url:'/validateresapa',
  data:{'resdate':resdate,
        'apaid':apaid},
     
  success: function(data){
 if(resdate != ""){
    if (data.valid_resdate){
       $('#error').show();
       $('#id_login_date').addClass('error_date');
    }
    else if (resdate < data.today){
          $('#error').show();
          $('#error').text("التاريخ غير صالح");
          $('#id_login_date').addClass('error_date'); 
         }      
    else{
      $('#error').hide();
      $('#id_login_date').removeClass('error_date');
    }
  }
  else{
    $('#error').hide();
      $('#id_login_date').removeClass('error_date');
  }
}      
 });

}); 
$('#id_exit_date').change(function(){
  var exdate = $('#id_exit_date').val();
  var lodate = $('#id_login_date').val();
  if (exdate != ""){
    if(exdate < lodate){
      $('#id_exit_date').addClass('error_date'); 
      $('#errorex').show();
    }
    else {
      $('#id_exit_date').removeClass('error_date'); 
      $('#errorex').hide();
    }
  }
  else{
    $('#id_exit_date').removeClass('error_date'); 
      $('#errorex').hide();
  }
});

</script>

{% endblock %}

templates/pages/booking/book_cha.html
{% extends 'base.html' %}

{% block content%}


<form class="form_CB" method="post">
  {% csrf_token %}
    <div class="container_CB1">
      <div class="input-field_CB2" style="width: 40%;">
          <label class="label_CB3">الاسم الكامل</label>
          {{form.customers}}
          <a href="{% url 'clientdata' %}" style=" color: #000;">
          <i class="fas fa-add"></i>
        </a> 
      </div>
  
  <div class="section_CB3">
    <div class="input-field_CB2" style="position: absolute;top: 35%; right: 27%;">
      <label class="label_CB3">تاريخ الحجز</label>
      <input type="text" id="date_of_enter" style="width: 214%; position: absolute;top: 100%; right: 15%;">
    </div>
    <div class="input-field_CB2" style="position: absolute;top: 35.3%; right: 40%; width: 10%;">
        <label class="label_CB3">رقم الشاليه </label>
        <select id="nationality" >
            <option value="first_bunch">شاليه 1 </option>
            <option value="second_bunch">شاليه 2  </option>
            <option value="third_bunch">شاليه 3  </option>

        </select>
      </div>
    <div class="input-field_CB2" style="position: absolute; top: 35.3%; right: 55%; width: 90px; ">
      <label class="label_CB3">وقت الدخول</label>
        <input type="text" id="id_login_time" style="width: 110px;">
      </div>
  </div>
  </div>

  <div class="section_CB3">
      
    </div>
    <div class="input-field_CB2"  style="position: absolute; left: 350px; top: 35.3%; width: 119px;" >
      <label class="label_CB3">وقت الخروج</label>
        <input type="text" id="id_exit_time" >
      </div>
  </div>
<div class="section_B5">
  <div class="input-field_CB2" style="margin-top: 14%; width: 330px;">
    <label class="label_CB3">اختيار الباقة </label>
    {{form.bunch}}
  </div>
  <div class="input-field_CB2" style="margin-right: 90px; margin-top: 14%" >
    <label class="label_CB3" style="padding-right: 8%;">السعر </label>
    {{form.res_cha_price}}
  </div>
</div>
  
  
  <div class="input-field_CB2">
    <label class="label_CB3">ملاحظات </label>
    <textarea placeholder="أكتب الملاحظات" style="width: calc(100% - 5%);"></textarea>
  </div>

  <div class="button-container_CB5">
    <button type="submit" class="button_CB5">حجز الشاليه</button>
  </div>

</form>


{% endblock %}

{% block javascript %}
<script>
  $("#date_of_enter").change(function(){
 var resdate = $(this).val();
 $.ajax({
  dataType:'json',
  url:'/daterescha',
  data:{'resdate':resdate},
  
  success: function(data){
    console.log(data.eq);
   
  }        
 });
}); 

</script>

<script>
  $("#id_bunch").change(function(){
   var idbunch = $(this).val();
   $.ajax({
    dataType:'json',
    url:'/validate',
    data:{'idbunch':idbunch},
    
    success: function(data){
     $("#id_res_cha_price").val(data.pr);
     $("#id_login_time").val(data.en);
     $("#id_exit_time").val(data.ex); 
     $("#price").text(data.pr);   
    }        
   });
  });  
</script>

{% endblock %}

templates/pages/booking/chalih_book.html
{% extends 'base.html' %}



{% block content%}


<form class="form_CB" method="POST" dir="rtl">
              {% csrf_token %}
              <div class="input-field_CB2" style="direction: rtl;">
                <label class="label_CB3" style="margin-left: 530px;">{{form.customers.label}}</label>
               {{form.customers}}
               <a href="{% url 'clientdata' %}" style=" color: #000;">
                <i class="fas fa-add"></i>
                </a>
               </div>

               <div class="section_CB3">
                  <div class="input-field_CB2" style=" position: relative; left: 360px; bottom: 5px; width: 170px;">
                  <label class="label_CB3">{{form.res_cha_date.label}} </label>
                  {{form.res_cha_date}}
                  <p id="error" style="font-size: small; float: right; margin-right: 8px; color: #f10202; display: none;">هذا التاريخ محجوز </p>
                  </div>

                  <div class="input-field_CB2" style="top: 223px; position: absolute; right: 770px; width: 119px;">
                  <label class="label_CB3"> {{form.login_time.label}} </label>
                  {{form.login_time}}
                  </div>
                </div>

                <div class="section_CB3">
                  <div class="input-field_CB2"  style="margin-top: 17px; width: 119px;">
                    <label class="label_CB3">{{form.exit_time.label}}</label>
                    {{form.exit_time}}
                    </div>
                </div>

                <div class="section_B5">
                  <div class="input-field_CB2" style=" width: 330px; ">
                    <label class="label_CB3">{{form.bunch.label}}</label>
                    {{form.bunch}}
                  </div>
                  <div class="input-field_CB2" style="margin-right: 100px; margin-top: 28px; " >
                    <label class="label_CB3" style="position: absolute; left: 600px;">{{form.res_cha_price.label}}</label>
                    {{form.res_cha_price}}
                  </div>
                </div>
                <div style="display: none;">
                  {{form.chalits}}
                  {{form.user}}
                </div>
                
                
  <div class="button-container_CB5" style="margin-top: 20px;">
    <button type="submit" class="button_CB5">حجز الشاليه</button>
  </div>
  
  <div class="container_B9" style="height: 473px; width: 300px;" >
  
    <label class="label_B9" style="position: absolute; right: 5px;">معلومات الشاليه</label> <br><br>
    <hr>
    <label class="label_B9_1" style="position: absolute; right: 2px"> الطابق :   {{bookch.cha_floor}}</label>
    <label class="label_B9_1" style="position: absolute; left: 40px;">   {{bookch.cha_name}}   </label>
    <label class="label_B9_1"  style="position: absolute; top: 150px; right: 2px; margin-top: 25px;"> وصف الشاليه :{{bookch.cha_discrip}} </label><br>
    <br> <br> <br> <br> <br> <hr> <br> 
    <label class="label_B9_1" style="font-size: x-large;padding-top: 10px; position: absolute; right: 2px; bottom: 137px;"> الإجمالي  : </label> 
    <label class="label_B9_1" id="price" style="font-size: x-large; font-weight: bold; margin-top: 10px;position: absolute; right: 115px;bottom: 135px;">00.000 </label> <br>
    <label class="label_B9_1" style="font-size: larger;position: absolute; bottom: 80px; right: 2px;">المدفوع :</label>
    <label class="label_B9_1" style="font-size: larger; font-weight: bold; margin-top: 10px;position: absolute; right: 115px;bottom: 80px;">00.000 </label>
    <label class="label_B9_1" style="font-size: larger;position: absolute; bottom: 40px; right: 2px;">المتبقي :</label>
    <label class="label_B9_1" style="font-size: larger; font-weight: bold; margin-top: 10px;position: absolute; right: 115px;bottom: 40px;">00.000 </label>
  </div>
  

</form>

{% endblock %}

{% block javascript %}

<script>
  $("#id_bunch").change(function(){
   var idbunch = $(this).val();
   $.ajax({
    dataType:'json',
    url:'/validate',
    data:{'idbunch':idbunch},
    
    success: function(data){
     $("#id_res_cha_price").val(data.pr);
     $("#id_login_time").val(data.en);
     $("#id_exit_time").val(data.ex); 
     $("#price").text(data.pr);   
    }        
   });
  });  
</script>

<script>
    $("#id_res_cha_date").change(function(){
   var resdate = $(this).val();
   var chaid = $('#id_chalits').val();
   $.ajax({
    dataType:'json',
    url:'/validaterescha',
    data:{'resdate':resdate,
          'chaid':chaid},
    
    success: function(data){
    
      if (data.valid_resdate ){
         $('#error').show();
         $('#id_res_cha_date').addClass('error_date');       
      }
      else if (resdate < data.today){
          $('#error').show();
          $('#error').text("التاريخ غير صالح");
          $('#id_res_cha_date').addClass('error_date'); 
         }
      else if (resdate = ""){
        $('#error').hide();
        $('#id_res_cha_date').removeClass('error_date');
      }
      else{
        $('#error').hide();
        $('#id_res_cha_date').removeClass('error_date');
      }
    }        
   });
  }); 
  
</script>

{% endblock %}